/*
 * generated by Xtext 2.36.0
 */
package miniProjet.ui.tests;

import com.google.inject.Injector;
import miniProjet.pdlXtext.ui.internal.PdlXtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class PDLXTextUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PdlXtextActivator.getInstance().getInjector("miniProjet.PDLXText");
	}

}
