/*
 * generated by Xtext 2.32.0
 */
package miniProjet.ui.tests;

import com.google.inject.Injector;
import miniProjet.simplepdl.pdl.ui.internal.PdlActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class PDLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PdlActivator.getInstance().getInjector("miniProjet.PDL");
	}

}
