/**
 * generated by Xtext 2.36.0
 */
package miniProjet.pDLXText.impl;

import miniProjet.pDLXText.PDLXTextPackage;
import miniProjet.pDLXText.ProcessElement;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Process Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ProcessElementImpl extends MinimalEObjectImpl.Container implements ProcessElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProcessElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PDLXTextPackage.Literals.PROCESS_ELEMENT;
  }

} //ProcessElementImpl
