/*
 * generated by Xtext 2.36.0
 */
package miniProjet.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import miniProjet.PDLXTextRuntimeModule;
import miniProjet.PDLXTextStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PDLXTextIdeSetup extends PDLXTextStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PDLXTextRuntimeModule(), new PDLXTextIdeModule()));
	}
	
}
