/*
 * generated by Xtext 2.36.0
 */
package miniProjet;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PDLXTextRuntimeModule extends AbstractPDLXTextRuntimeModule {
}
