/*
 * generated by Xtext 2.36.0
 */
package miniProjet;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PDLXTextStandaloneSetup extends PDLXTextStandaloneSetupGenerated {

	public static void doSetup() {
		new PDLXTextStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
