/**
 * generated by Xtext 2.36.0
 */
package miniProjet.pDLXText;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Guidance</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link miniProjet.pDLXText.Guidance#getTexte <em>Texte</em>}</li>
 *   <li>{@link miniProjet.pDLXText.Guidance#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see miniProjet.pDLXText.PDLXTextPackage#getGuidance()
 * @model
 * @generated
 */
public interface Guidance extends ProcessElement
{
  /**
   * Returns the value of the '<em><b>Texte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Texte</em>' attribute.
   * @see #setTexte(String)
   * @see miniProjet.pDLXText.PDLXTextPackage#getGuidance_Texte()
   * @model
   * @generated
   */
  String getTexte();

  /**
   * Sets the value of the '{@link miniProjet.pDLXText.Guidance#getTexte <em>Texte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Texte</em>' attribute.
   * @see #getTexte()
   * @generated
   */
  void setTexte(String value);

  /**
   * Returns the value of the '<em><b>Elements</b></em>' reference list.
   * The list contents are of type {@link miniProjet.pDLXText.ProcessElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' reference list.
   * @see miniProjet.pDLXText.PDLXTextPackage#getGuidance_Elements()
   * @model
   * @generated
   */
  EList<ProcessElement> getElements();

} // Guidance
