/**
 * generated by Xtext 2.36.0
 */
package miniProjet.pDLXText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Need</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link miniProjet.pDLXText.Need#getQuantityNeeded <em>Quantity Needed</em>}</li>
 *   <li>{@link miniProjet.pDLXText.Need#getRessource <em>Ressource</em>}</li>
 * </ul>
 *
 * @see miniProjet.pDLXText.PDLXTextPackage#getNeed()
 * @model
 * @generated
 */
public interface Need extends ProcessElement
{
  /**
   * Returns the value of the '<em><b>Quantity Needed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantity Needed</em>' attribute.
   * @see #setQuantityNeeded(int)
   * @see miniProjet.pDLXText.PDLXTextPackage#getNeed_QuantityNeeded()
   * @model
   * @generated
   */
  int getQuantityNeeded();

  /**
   * Sets the value of the '{@link miniProjet.pDLXText.Need#getQuantityNeeded <em>Quantity Needed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantity Needed</em>' attribute.
   * @see #getQuantityNeeded()
   * @generated
   */
  void setQuantityNeeded(int value);

  /**
   * Returns the value of the '<em><b>Ressource</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ressource</em>' reference.
   * @see #setRessource(Ressource)
   * @see miniProjet.pDLXText.PDLXTextPackage#getNeed_Ressource()
   * @model
   * @generated
   */
  Ressource getRessource();

  /**
   * Sets the value of the '{@link miniProjet.pDLXText.Need#getRessource <em>Ressource</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ressource</em>' reference.
   * @see #getRessource()
   * @generated
   */
  void setRessource(Ressource value);

} // Need
