/**
 * generated by Xtext 2.36.0
 */
package miniProjet.pDLXText;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link miniProjet.pDLXText.Process#getName <em>Name</em>}</li>
 *   <li>{@link miniProjet.pDLXText.Process#getProcessElements <em>Process Elements</em>}</li>
 * </ul>
 *
 * @see miniProjet.pDLXText.PDLXTextPackage#getProcess()
 * @model
 * @generated
 */
public interface Process extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see miniProjet.pDLXText.PDLXTextPackage#getProcess_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link miniProjet.pDLXText.Process#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Process Elements</b></em>' containment reference list.
   * The list contents are of type {@link miniProjet.pDLXText.ProcessElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Process Elements</em>' containment reference list.
   * @see miniProjet.pDLXText.PDLXTextPackage#getProcess_ProcessElements()
   * @model containment="true"
   * @generated
   */
  EList<ProcessElement> getProcessElements();

} // Process
