/*
 * generated by Xtext 2.32.0
 */
package miniProjet.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPDLScopeProvider extends DelegatingScopeProvider {
}
