/*
 * generated by Xtext 2.36.0
 */
package miniProjet.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPDLXTextScopeProvider extends DelegatingScopeProvider {
}
