/*
 * generated by Xtext 2.36.0
 */
package miniProjet.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractPDLXTextValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(miniProjet.pDLXText.PDLXTextPackage.eINSTANCE);
		return result;
	}
}
