/*
 * generated by Xtext 2.32.0
 */
package miniProjet.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PDLUiModule extends AbstractPDLUiModule {

	public PDLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
