/*
 * generated by Xtext 2.32.0
 */
package miniProjet.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import miniProjet.PDLRuntimeModule;
import miniProjet.PDLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PDLIdeSetup extends PDLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PDLRuntimeModule(), new PDLIdeModule()));
	}
	
}
