/**
 * generated by Xtext 2.32.0
 */
package miniProjet.pDL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see miniProjet.pDL.PDLPackage#getProcessElement()
 * @model
 * @generated
 */
public interface ProcessElement extends EObject
{
} // ProcessElement
