/**
 * generated by Xtext 2.32.0
 */
package miniProjet.pDL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ressource</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link miniProjet.pDL.Ressource#getName <em>Name</em>}</li>
 *   <li>{@link miniProjet.pDL.Ressource#getQuantity <em>Quantity</em>}</li>
 * </ul>
 *
 * @see miniProjet.pDL.PDLPackage#getRessource()
 * @model
 * @generated
 */
public interface Ressource extends ProcessElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see miniProjet.pDL.PDLPackage#getRessource_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link miniProjet.pDL.Ressource#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantity</em>' attribute.
   * @see #setQuantity(int)
   * @see miniProjet.pDL.PDLPackage#getRessource_Quantity()
   * @model
   * @generated
   */
  int getQuantity();

  /**
   * Sets the value of the '{@link miniProjet.pDL.Ressource#getQuantity <em>Quantity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantity</em>' attribute.
   * @see #getQuantity()
   * @generated
   */
  void setQuantity(int value);

} // Ressource
