/**
 * generated by Xtext 2.32.0
 */
package miniProjet.pDL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Work Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link miniProjet.pDL.WorkDefinition#getName <em>Name</em>}</li>
 *   <li>{@link miniProjet.pDL.WorkDefinition#getNeed <em>Need</em>}</li>
 * </ul>
 *
 * @see miniProjet.pDL.PDLPackage#getWorkDefinition()
 * @model
 * @generated
 */
public interface WorkDefinition extends ProcessElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see miniProjet.pDL.PDLPackage#getWorkDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link miniProjet.pDL.WorkDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Need</b></em>' containment reference list.
   * The list contents are of type {@link miniProjet.pDL.Need}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Need</em>' containment reference list.
   * @see miniProjet.pDL.PDLPackage#getWorkDefinition_Need()
   * @model containment="true"
   * @generated
   */
  EList<Need> getNeed();

} // WorkDefinition
