/*
 * generated by Xtext 2.36.0
 */
package miniProjet.parser.antlr;

import com.google.inject.Inject;
import miniProjet.parser.antlr.internal.InternalPDLXTextParser;
import miniProjet.services.PDLXTextGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class PDLXTextParser extends AbstractAntlrParser {

	@Inject
	private PDLXTextGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPDLXTextParser createParser(XtextTokenStream stream) {
		return new InternalPDLXTextParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Process";
	}

	public PDLXTextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PDLXTextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
