/*
 * generated by Xtext 2.36.0
 */
package miniProjet.ui;

import com.google.inject.Injector;
import miniProjet.pdlXtext.ui.internal.PdlXtextActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PDLXTextExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(PdlXtextActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		PdlXtextActivator activator = PdlXtextActivator.getInstance();
		return activator != null ? activator.getInjector(PdlXtextActivator.MINIPROJET_PDLXTEXT) : null;
	}

}
