/*
 * generated by Xtext 2.36.0
 */
package miniProjet.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PDLXTextUiModule extends AbstractPDLXTextUiModule {

	public PDLXTextUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
